#server:
#  servlet:
#    context-path: /
#  port:
#    5001
#
#spring:
#  application:
#    name: user-service
#  datasource:
#    url: jdbc:postgresql://localhost:5432/loan
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#openapi:
#  service:
#    title: user-service doc
#    version: 1.0.0
#    url: http://localhost:5001
#
#springdoc:
#  api-docs:
#    path: /user-service/v3/api-docs
#  swagger-ui:
#    path: /user-service/swagger-ui.html
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
