server:
  servlet:
    context-path: /
  port:
    8080

spring:
  data:
    redis:
      port: 6379
      host: localhost
      timeout: 300000
      password: 12345
      ssl:
        enabled: false
  application:
    name: api-gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/** , /loan-service/v3/api-docs
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/** , /user-service/v3/api-docs
          filters:
            - StripPrefix=1
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            key-resolver: "#{@remoteAddressKeyResolver}"

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /loan-service/v3/api-docs
        name: Loan Service
        primaryName: Loan Service
      - url: /user-service/v3/api-docs
        name: User Service
        primaryName: User Service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  secret: 2NufeUmpnahWB64CpM/1j3zMTtRBzWAShK0Lo9avMFyC3nqYjyK67Rr6w1ja9TrAyP0/ko0ngMPwDD3uRH/YCw==


logging:
  level:
    org.springframework: DEBUG


