server:
  servlet:
    context-path: /
  port:
    5000

spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://localhost:5432/loan
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /loan-service/v3/api-docs
  swagger-ui:
    path: /loan-service/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


